# Generated by Django 2.0 on 2017-12-18 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Project Title')),
                ('description', models.CharField(max_length=1024, verbose_name='Project Description')),
                ('pi_name', models.CharField(max_length=128, verbose_name='PI Name')),
                ('pi_email', models.EmailField(max_length=254, verbose_name='PI Email')),
                ('institution_reference', models.CharField(max_length=128, verbose_name='Owning institution project reference')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('economic_user', models.BooleanField(default=False)),
                ('requirements_software', models.CharField(max_length=512)),
                ('requirements_gateways', models.CharField(max_length=512)),
                ('requirements_training', models.CharField(max_length=512)),
                ('requirements_onboarding', models.CharField(max_length=512)),
                ('allocation_rse', models.BooleanField(default=False, verbose_name='RSE available to?')),
                ('allocation_cputime', models.PositiveIntegerField(verbose_name='CPU time allocation')),
                ('allocation_storage', models.PositiveIntegerField(verbose_name='Project group storage allocation')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Category Name')),
                ('description', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Source Name')),
                ('description', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Status')),
                ('description', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSystemAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_allocated', models.DateField()),
                ('date_unallocated', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(default=datetime.date(9999, 12, 31))),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Project')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('number_of_cores', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='SCW Username')),
                ('common_name', models.CharField(max_length=128, verbose_name='Common Name')),
                ('email', models.EmailField(max_length=254)),
                ('disabled', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='projectusermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.User'),
        ),
        migrations.AddField(
            model_name='projectsystemallocation',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.System'),
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_systems',
            field=models.ManyToManyField(through='reg.ProjectSystemAllocation', to='reg.System'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.ProjectCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.ProjectFundingSource'),
        ),
        migrations.AddField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Institution'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='reg.ProjectUserMembership', to='reg.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_as_tech_lead', to='reg.User'),
        ),
    ]
