# Generated by Django 4.2.3 on 2025-02-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_domain', models.CharField(blank=True, max_length=255)),
                ('academic', models.BooleanField(default=False)),
                ('commercial', models.BooleanField(default=False)),
                ('service_provider', models.BooleanField(default=False)),
                ('identity_provider', models.URLField(blank=True, verbose_name='Shibboleth Identity Provider')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
